### ISSUE TITLE
[Bug]: Inconsistent results when using Ray manager

### ISSUE THREAD

**Issue by wigging** [pybamm-team/liionpack#170] opened 2022-07-13 16:02 UTC
### liionpack Version

0.3.2

### Python Version

3.9.12

### Describe the bug

I get inconsistent results and sometimes errors when using the Ray manager. I don't have these issues when using the Casadi manager. See the example below for more information.

### Steps to Reproduce

This example works fine when using the Casadi manager.

```python
import liionpack as lp
import pybamm
import numpy as np

def main():

    # Define parameters
    Np = 16
    Ns = 2
    Iapp = 20
    nproc = 8
    manager = 'casadi'

    # Generate the netlist
    netlist = lp.setup_circuit(Np=Np, Ns=Ns)

    # Define additional output variables
    output_variables = [
        'Volume-averaged cell temperature [K]']

    # Define a cycling experiment using PyBaMM
    experiment = pybamm.Experiment([
        f'Charge at {Iapp} A for 30 minutes',
        'Rest for 15 minutes',
        f'Discharge at {Iapp} A for 30 minutes',
        'Rest for 30 minutes'],
        period='10 seconds')

    # Define the PyBaMM parameters
    parameter_values = pybamm.ParameterValues("Chen2020")
    inputs = {"Total heat transfer coefficient [W.m-2.K-1]": np.ones(Np * Ns) * 10}

    # Solve the pack
    output = lp.solve(netlist=netlist,
                      sim_func=lp.thermal_simulation,
                      parameter_values=parameter_values,
                      experiment=experiment,
                      output_variables=output_variables,
                      initial_soc=0.5,
                      inputs=inputs,
                      nproc=nproc,
                      manager=manager)

    # Plot the pack and individual cell results
    lp.plot_pack(output)
    lp.plot_cells(output)
    lp.show_plots()

if __name__ == '__main__':
    main()
```

Here are the plots generated from the above example.

<img width="1118" alt="casadi" src="https://user-images.githubusercontent.com/6828967/178777349-b4c35915-7137-48a1-a5f9-f4815ab6e89e.png">

I get the following plots using the Ray manager for the same example.

<img width="1117" alt="ray" src="https://user-images.githubusercontent.com/6828967/178777675-cd0f674f-5a91-41f8-b8eb-7c766dae645a.png">

Sometimes I get the error shown below when using the Ray manager and I eventually have to abort the simulation.

```
Stepping simulation:  52%|█████████████████████████████████████████▏                                      | 325/631 [00:10<00:09, 32.88it/s](RayActor pid=94841) psetup failed: .../casadi/interfaces/sundials/cvodes_interface.cpp:650: 'jacF' calculation failed
(RayActor pid=94841) psetup failed: .../casadi/interfaces/sundials/cvodes_interface.cpp:650: 'jacF' calculation failed
(RayActor pid=94841) psetup failed: .../casadi/interfaces/sundials/cvodes_interface.cpp:650: 'jacF' calculation failed
(RayActor pid=94841) psetup failed: .../casadi/interfaces/sundials/cvodes_interface.cpp:650: 'jacF' calculation failed
(RayActor pid=94841) psetup failed: .../casadi/interfaces/sundials/cvodes_interface.cpp:650: 'jacF' calculation failed
```

### Expected behaviour

Simulation results when using the Casadi or Ray manager should be the same.

**Comment by TomTranter** [comment] 2022-07-29 10:01
Hi @wigging thanks for raising this issue. I don't have a lot of time to look at this right now but will make it high priority to sort out

**Comment by wigging** [comment] 2022-09-14 17:50
Any updates on this?

**Comment by TomTranter** [comment] 2022-09-14 18:17
Nope sorry haven’t had a chance lately. Did you try debugging it at all?

**Comment by wigging** [comment] 2022-09-14 18:37
It's difficult to debug because the problem doesn't always occur. Best chance of figuring this out is to go back to a version of liionpack where there are no problems using Ray. Then see what changes were introduced in the code that could be causing the issue.

**Comment by wigging** [comment] 2022-09-14 18:41
Can someone else verify this issue with the latest liionpack version or am I the only person having this problem?

**Comment by TomTranter** [comment] 2022-09-14 18:53
I’ll try tomorrow. So do you restart the kernel each time? Sounds like
something could be hanging around if you get different results running same
script?

**Comment by wigging** [comment] 2022-09-14 19:00
I ran the example I gave above from the terminal prompt. Everything exits when the simulation is done. Doesn't matter if you restart the terminal (kernel). Either way I never had this issue until the recent release. Were there any updates to Ray that could cause this?

**Comment by TomTranter** [comment] 2022-09-14 19:06
No not much changed…

**Comment by TomTranter** [comment] 2022-09-16 16:54
@wigging it seems like the problem is in PyBaMM. I traced back to a working version on 7 Jun, on the 8th this PR was merged  https://github.com/pybamm-team/PyBaMM/pull/1978 and causes the issue as far as I can tell. Unfortunately 72 files were changed in this PR!

**Comment by TomTranter** [comment] 2022-09-16 16:56
N.B I also had to roll back liionpack to 9th Jun

**Comment by wigging** [comment] 2022-09-20 00:58
I tried going back to liionpack v0.3.1 but I get errors for
`AttributeError: 'LithiumIonParameters' object has no attribute 'C_n_init'`
Do you remember which older version of PyBaMM is compatible with the older liionpack?

**Comment by TomTranter** [comment] 2022-09-20 13:11
I think 22.5 should work
@tinosulzer anything you can think of in https://github.com/pybamm-team/PyBaMM/pull/1978 that might be causing this issue?

**Comment by tinosulzer** [comment] 2022-09-21 14:59
I can't find what in that issue might be causing problems. However, I think there is a bug related to inputs. This works every time:
```python3
import liionpack as lp
import pybamm
import numpy as np

lp.set_logging_level('NOTICE')

# Generate the netlist
netlist = lp.setup_circuit(Np=4, Ns=2)

# Define a cycling experiment using PyBaMM
experiment = pybamm.Experiment([f'Charge at 5 A for 30 minutes'])

# Define the PyBaMM parameters
parameter_values = pybamm.ParameterValues("Chen2020")
# inputs = {"Total heat transfer coefficient [W.m-2.K-1]": np.ones(8) * 10}

# Solve the pack
output = lp.solve(netlist=netlist,
                    # sim_func=lp.thermal_simulation,
                    sim_func=lp.basic_simulation,
                    parameter_values=parameter_values,
                    experiment=experiment,
                    initial_soc=0.5,
                    # inputs=inputs,
                    nproc=8,
                    manager='ray')

# Plot the pack and individual cell results
lp.plot_cells(output)
lp.show_plots()
```
this fails intermittently (keeping everything else the same, adding thermal model, with inputs to thermal model):
```python3
output = lp.solve(netlist=netlist,
                    sim_func=lp.thermal_simulation, # changed to thermal simulation
                    parameter_values=parameter_values,
                    experiment=experiment,
                    initial_soc=0.5,
                    inputs={"Total heat transfer coefficient [W.m-2.K-1]": np.ones(8) * 10}, # added inputs
                    nproc=8,
                    manager='ray')
```
and this works (keeping everything else the same, keeping thermal model, but no inputs to thermal model)
```python3
def custom_thermal_simulation(parameter_values=None):
    """
    Create a PyBaMM simulation set up for integration with liionpack

    Args:
        parameter_values (pybamm.ParameterValues):
            The default is None.

    Returns:
        pybamm.Simulation:
            A simulation that can be solved individually or passed into the
            liionpack solve method

    """
    # Create the pybamm model
    model = pybamm.lithium_ion.SPMe(
        options={
            "thermal": "lumped",
            "timescale": 10,
        }
    )

    # Add events to the model
    model = lp.add_events_to_model(model)

    # Set up parameter values
    if parameter_values is None:
        parameter_values = pybamm.ParameterValues("Chen2020")

    # Set up solver and simulation
    solver = pybamm.CasadiSolver(mode="safe")
    sim = pybamm.Simulation(
        model=model,
        parameter_values=parameter_values,
        solver=solver,
    )
    return sim

# Solve the pack
output = lp.solve(netlist=netlist,
                    sim_func=custom_thermal_simulation,
                    parameter_values=parameter_values,
                    experiment=experiment,
                    initial_soc=0.5,
                    nproc=8,
                    manager='ray')
```

**Comment by TomTranter** [comment] 2022-09-21 16:08
Oh ok, thanks I'll look into this tomorrow

**Comment by tinosulzer** [comment] 2022-09-21 18:11
This should be fixed by the PR above. https://github.com/pybamm-team/PyBaMM/issues/2310 should be done in pybamm to avoid errors like this in future

**Closed** 2022-09-22 08:57 UTC
Labels: bug
